project:
  type: website
  output-dir: docs

website:
  title: "Tour de France 2023 Fantasy sportif"
  navbar:
    left:
      - href: Scoring.qmd
        text: Scoring system
      - href: Stages.qmd
        text: Stage breakdowns

format:
  html:
      theme: minty # browse these here: https://quarto.org/docs/output-formats/html-themes.html
      max-width: 1800px # adjust if your plots don't fit or you want more or less whitespace
      toc: true # do you want a table of contents, by default it floats as you scroll
      toc-location: left # where should it be displayed
      toc-title: "Sections" 
      code-fold: true # fold code up for neater display
      smooth-scroll: true 
      #embed-resources: true # output doc contains all info needed to display html